// Shared guide data — used by /guias/[slug] (ES) and /en/guias/[slug] (EN)

export const GUIDES = {
  'testamento-simple': {
    emoji: '📄',
    color: '#1E3A8A',
    es: {
      title: 'Guía Completa: Testamento Simple en California',
      subtitle: 'Todo lo que necesita saber sobre Last Will & Testament — 2026',
      desc: 'Aprenda qué es un testamento simple, cuándo lo necesita, qué incluye bajo las leyes de California, y cómo preparar el suyo en línea hoy mismo.',
      bullets: ['¿Qué es y para qué sirve?', 'Requisitos legales en California 2026', 'Qué incluye su testamento', '¿Cuándo NO es suficiente un testamento?', 'Preguntas frecuentes y respuestas claras'],
      pages: '8 páginas',
      docUrl: '/simple-will',
      docLabel: 'Preparar Mi Testamento — $149',
      metaTitle: 'Guía: Testamento Simple en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre el testamento simple en California. Requisitos legales, qué incluye y cómo prepararlo en línea. Descargue el PDF gratis.',
    },
    en: {
      title: 'Complete Guide: Simple Will in California',
      subtitle: 'Everything you need to know about Last Will & Testament — 2026',
      desc: 'Learn what a simple will is, when you need one, what it includes under California law, and how to prepare yours online today.',
      bullets: ['What is a will and why do you need one?', 'Legal requirements in California 2026', 'What your will includes', 'When a simple will is NOT enough', 'FAQs with clear answers'],
      pages: '8 pages',
      docUrl: '/en/simple-will',
      docLabel: 'Prepare My Will — $149',
      metaTitle: 'Guide: Simple Will in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to last will and testament in California. Legal requirements, what\'s included, and how to prepare yours online. Download PDF free.',
    },
  },
  'testamento-traspaso': {
    emoji: '📜',
    color: '#7C3AED',
    es: {
      title: 'Guía Completa: Pour-Over Will en California',
      subtitle: 'El complemento esencial de su Fideicomiso en Vida — 2026',
      desc: 'Descubra por qué un Pour-Over Will es indispensable si tiene un fideicomiso, cómo funciona, y qué pasa con sus bienes si no lo tiene.',
      bullets: ['¿Qué es un Pour-Over Will?', 'Por qué lo necesita con su fideicomiso', 'Qué incluye el documento', '¿Pasan los bienes por probate?', 'Diferencia con testamento simple'],
      pages: '7 páginas',
      docUrl: '/pour-over-will',
      docLabel: 'Preparar Mi Pour-Over Will — $199',
      metaTitle: 'Guía: Pour-Over Will en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre el Pour-Over Will en California. Por qué es esencial con un fideicomiso y cómo prepararlo. PDF gratis.',
    },
    en: {
      title: 'Complete Guide: Pour-Over Will in California',
      subtitle: 'The essential complement to your Living Trust — 2026',
      desc: 'Discover why a Pour-Over Will is essential if you have a trust, how it works, and what happens to your assets without one.',
      bullets: ['What is a Pour-Over Will?', 'Why you need it alongside your trust', 'What the document includes', 'Do assets go through probate?', 'Difference from a simple will'],
      pages: '7 pages',
      docUrl: '/en/pour-over-will',
      docLabel: 'Prepare My Pour-Over Will — $199',
      metaTitle: 'Guide: Pour-Over Will in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to pour-over will in California. Why it\'s essential with a living trust and how to prepare yours online. Download PDF free.',
    },
  },
  'hipaa-authorization': {
    emoji: '🏥',
    color: '#DC2626',
    es: {
      title: 'Guía Completa: Autorización HIPAA en California',
      subtitle: 'Acceso médico para su familia en emergencias — 2026',
      desc: 'Entienda por qué la Autorización HIPAA es crítica, especialmente para la comunidad latina. Sin este documento, su familia no puede acceder a su información médica.',
      bullets: ['¿Qué es la ley HIPAA?', 'Por qué es esencial para familias latinas', 'Quién puede ser su agente médico', 'Diferencia con el poder médico', 'Cómo revocarla si cambia de opinión'],
      pages: '7 páginas',
      docUrl: '/hipaa-authorization',
      docLabel: 'Preparar Mi Autorización HIPAA — $99',
      metaTitle: 'Guía: Autorización HIPAA en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre la Autorización HIPAA en California. Qué es, para qué sirve, y cómo dar acceso médico a su familia. PDF gratis.',
    },
    en: {
      title: 'Complete Guide: HIPAA Authorization in California',
      subtitle: 'Medical access for your family in emergencies — 2026',
      desc: 'Understand why HIPAA Authorization is critical — especially for Latino families. Without this document, your family cannot access your medical information.',
      bullets: ['What is the HIPAA law?', 'Why it\'s essential for Latino families', 'Who can be your medical agent', 'Difference from a medical power of attorney', 'How to revoke it if you change your mind'],
      pages: '7 pages',
      docUrl: '/en/hipaa-authorization',
      docLabel: 'Prepare My HIPAA Authorization — $99',
      metaTitle: 'Guide: HIPAA Authorization in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to HIPAA Authorization in California. What it is, why you need it, and how to authorize family access to your medical records.',
    },
  },
  'certificacion-fideicomiso': {
    emoji: '🔏',
    color: '#059669',
    es: {
      title: 'Guía Completa: Certificación de Fideicomiso',
      subtitle: 'El documento que los bancos siempre piden — California 2026',
      desc: 'Sepa por qué todos los bancos, compañías de títulos y instituciones requieren la Certificación de Fideicomiso, y qué información debe incluir.',
      bullets: ['¿Qué es y por qué la piden?', 'Diferencia con el fideicomiso completo', 'Qué información incluye', 'Cuántas copias necesita', 'Cuándo actualizar su certificación'],
      pages: '7 páginas',
      docUrl: '/certification-of-trust',
      docLabel: 'Preparar Mi Certificación — $99',
      metaTitle: 'Guía: Certificación de Fideicomiso en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre la Certificación de Fideicomiso en California. Lo que bancos e instituciones requieren y cómo prepararlo. PDF gratis.',
    },
    en: {
      title: 'Complete Guide: Certification of Trust in California',
      subtitle: 'The document banks always require — California 2026',
      desc: 'Learn why every bank, title company, and institution requires a Certification of Trust, and what information it must include.',
      bullets: ['What is it and why do banks require it?', 'Difference from the full trust document', 'What information it includes', 'How many copies you need', 'When to update your certification'],
      pages: '7 pages',
      docUrl: '/en/certification-of-trust',
      docLabel: 'Prepare My Certification — $99',
      metaTitle: 'Guide: Certification of Trust in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to Certification of Trust in California. What banks and institutions require and how to prepare yours online. Download PDF free.',
    },
  },
  's-corporation': {
    emoji: '🏢',
    color: '#D97706',
    es: {
      title: 'Guía Completa: Formación de S-Corporation en California',
      subtitle: 'Proteja su negocio y optimice sus impuestos — 2026',
      desc: 'Todo lo que un empresario latino en California necesita saber sobre la S-Corporation: beneficios fiscales, requisitos, paquete completo de formación, y comparación con LLC.',
      bullets: ['¿Qué es una S-Corp y cómo funciona?', 'Beneficios fiscales clave', 'Requisitos de elegibilidad', 'S-Corp vs LLC vs C-Corp', 'Qué documentos incluye el paquete'],
      pages: '9 páginas',
      docUrl: '/s-corp-formation',
      docLabel: 'Formar Mi S-Corporation — $499',
      metaTitle: 'Guía: Formación de S-Corporation en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre la S-Corporation en California. Beneficios fiscales, requisitos y paquete completo. Descargue el PDF gratis.',
    },
    en: {
      title: 'Complete Guide: S-Corporation Formation in California',
      subtitle: 'Protect your business and optimize your taxes — 2026',
      desc: 'Everything a Latino entrepreneur in California needs to know about the S-Corporation: tax benefits, requirements, full formation package, and comparison with LLC.',
      bullets: ['What is an S-Corp and how does it work?', 'Key tax benefits', 'Eligibility requirements', 'S-Corp vs LLC vs C-Corp', 'What documents are included in the package'],
      pages: '9 pages',
      docUrl: '/en/s-corp-formation',
      docLabel: 'Form My S-Corporation — $499',
      metaTitle: 'Guide: S-Corporation Formation in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to S-Corporation formation in California. Tax benefits, requirements, and full formation package. Download PDF free.',
    },
  },
  'c-corporation': {
    emoji: '🏛️',
    color: '#B45309',
    es: {
      title: 'Guía Completa: Formación de C-Corporation en California',
      subtitle: 'La estructura para empresas con visión de crecimiento — 2026',
      desc: 'Descubra cuándo una C-Corp es mejor que una S-Corp o LLC, cómo atraer inversionistas, y qué documentos necesita para incorporarse correctamente en California.',
      bullets: ['¿Qué es una C-Corp?', 'Cuándo es la mejor opción', 'C-Corp vs S-Corp — comparación detallada', 'Requisitos para inversionistas', 'Paquete completo de incorporación'],
      pages: '8 páginas',
      docUrl: '/c-corp-formation',
      docLabel: 'Formar Mi C-Corporation — $499',
      metaTitle: 'Guía: Formación de C-Corporation en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre la C-Corporation en California. Cuándo es mejor que S-Corp o LLC, y cómo atraer inversionistas. PDF gratis.',
    },
    en: {
      title: 'Complete Guide: C-Corporation Formation in California',
      subtitle: 'The structure for growth-oriented businesses — 2026',
      desc: 'Discover when a C-Corp is better than an S-Corp or LLC, how to attract investors, and what documents you need to incorporate properly in California.',
      bullets: ['What is a C-Corp?', 'When it\'s the best option', 'C-Corp vs S-Corp — detailed comparison', 'Requirements for investors', 'Full incorporation package'],
      pages: '8 pages',
      docUrl: '/en/c-corp-formation',
      docLabel: 'Form My C-Corporation — $499',
      metaTitle: 'Guide: C-Corporation Formation in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to C-Corporation formation in California. When it\'s better than an S-Corp or LLC and how to attract investors. Download PDF free.',
    },
  },
  'actas-corporativas': {
    emoji: '📋',
    color: '#0284C7',
    es: {
      title: 'Guía Completa: Actas Corporativas en California',
      subtitle: 'Cómo proteger su corporate veil — Corporate Minutes 2026',
      desc: 'Aprenda por qué las actas corporativas son obligatorias, qué pasa si no las tiene, qué tipos necesita, y cómo prepararlas correctamente para su S-Corp o C-Corp.',
      bullets: ['¿Qué son y por qué son obligatorias?', 'Tipos de actas que necesita', '¿Qué es el "corporate veil"?', 'Con qué frecuencia prepararlas', 'Actas retroactivas — ¿es posible?'],
      pages: '8 páginas',
      docUrl: '/corporate-minutes',
      docLabel: 'Preparar Mis Actas Corporativas — $149',
      metaTitle: 'Guía: Actas Corporativas en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre las actas corporativas en California. Qué son, por qué son obligatorias, y cómo proteger su corporate veil. PDF gratis.',
    },
    en: {
      title: 'Complete Guide: Corporate Minutes in California',
      subtitle: 'How to protect your corporate veil — 2026',
      desc: 'Learn why corporate minutes are mandatory, what happens if you don\'t have them, which types you need, and how to prepare them correctly for your S-Corp or C-Corp.',
      bullets: ['What are they and why are they mandatory?', 'Types of minutes you need', 'What is the "corporate veil"?', 'How often to prepare them', 'Retroactive minutes — is it possible?'],
      pages: '8 pages',
      docUrl: '/en/corporate-minutes',
      docLabel: 'Prepare My Corporate Minutes — $149',
      metaTitle: 'Guide: Corporate Minutes in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to corporate minutes in California. Why they\'re mandatory and how to protect your corporate veil. Download PDF free.',
    },
  },
  'resolucion-bancaria': {
    emoji: '🏦',
    color: '#065F46',
    es: {
      title: 'Guía Completa: Resolución Bancaria Corporativa',
      subtitle: 'Lo que su banco requiere para cuentas e inversiones — 2026',
      desc: 'Entienda qué es la Resolución Bancaria, por qué todos los bancos la exigen, qué debe incluir, y cómo autorizar a representantes de su empresa correctamente.',
      bullets: ['¿Qué es y cuándo se necesita?', 'Por qué los bancos siempre la piden', 'Qué información incluye', 'Múltiples niveles de autoridad', 'Cuándo actualizarla'],
      pages: '7 páginas',
      docUrl: '/banking-resolution',
      docLabel: 'Preparar Mi Resolución Bancaria — $99',
      metaTitle: 'Guía: Resolución Bancaria en California 2026 | Multi Servicios 360',
      metaDesc: 'Guía gratuita en español sobre la Resolución Bancaria en California. Lo que su banco siempre pide para cuentas comerciales. PDF gratis.',
    },
    en: {
      title: 'Complete Guide: Corporate Banking Resolution',
      subtitle: 'What your bank requires for accounts and investments — 2026',
      desc: 'Understand what a Banking Resolution is, why all banks require it, what it must include, and how to authorize company representatives properly.',
      bullets: ['What is it and when is it needed?', 'Why banks always require it', 'What information it includes', 'Multiple levels of authority', 'When to update it'],
      pages: '7 pages',
      docUrl: '/en/banking-resolution',
      docLabel: 'Prepare My Banking Resolution — $99',
      metaTitle: 'Guide: Banking Resolution in California 2026 | Multi Servicios 360',
      metaDesc: 'Free bilingual guide to Banking Resolution in California. What your bank requires to open business accounts. Download PDF free.',
    },
  },
};

export function getGuide(slug, lang = 'es') {
  const g = GUIDES[slug];
  if (!g) return null;
  return { ...g[lang], emoji: g.emoji, color: g.color, slug };
}

export const ALL_SLUGS = Object.keys(GUIDES);
